version: '3.9'
services:
  postgres:
    image: vasire/postgres15_tds_fdw_temporal_tables:v1 #vasire/postgres15_tds_fdw:v5
    container_name: postgres15_tds_fdw_temporal_tables    
    # Определение политики перезапуска.  
    # no (Значение по умолчанию), что означает отключение автоматического перезапуска. 
    # always означает перезапуск в любом случае. 
    # on-failure означает перезапуск только в случае аварийной остановки контейнера. 
    # unless-stopped означает перезапуск контейнера во всех случаев, кроме преднамеренной остановки:    
    #restart: always     
    hostname: postgres   
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - TZ=${TZ}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./postgres-freetds:/etc/freetds
      - .:/docker-entrypoint-initdb.d
#    network_mode: "host"    
    ports:
      - 5432:5432
    links:
          - mssql
    deploy:
      resources:
        limits:
          memory: 256M
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
        - ${PGADMIN_PORT}:80
    volumes:
        - ./pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    # Определение политики перезапуска.  
    # no (Значение по умолчанию), что означает отключение автоматического перезапуска. 
    # always означает перезапуск в любом случае. 
    # on-failure означает перезапуск только в случае аварийной остановки контейнера. 
    # unless-stopped означает перезапуск контейнера во всех случаев, кроме преднамеренной остановки:    
    #restart: always 
#    network_mode: "host"
    ports:
      - "1433:1433"
      - "5022:5022"
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA : "Y"
      MSSQL_PID : "Developer"      
      TZ : ${TZ}
      MSSQL_LCID : "1049" # русский
      MSSQL_COLLATION : "Cyrillic_General_CI_AS"
      MSSQL_MEMORY_LIMIT_MB : "2048" #задает максимальный объем памяти (в МБ), который можно использовать SQL Server. По умолчанию он составляет 80% от общего объема физической памяти.
      MSSQL_TCP_PORT : "1433"      
      MSSQL_BACKUP_DIR : "/var/opt/sqlserver/backup" #Задайте расположение каталога резервного копирования по умолчанию.
      MSSQL_DATA_DIR : "/var/opt/sqlserver/data" #Перейдите в каталог, где создаются новые базы данных файлы данных SQL Server (.mdf).
      MSSQL_LOG_DIR : "/var/opt/sqlserver/log" #где создаются новые файлы журналов (LDF) базы данных SQL Server.
      # MSSQL_DUMP_DIR : "/var/opt/mssql/dumps" #где SQL Server будет Депонировать дампы памяти и другие файлы для устранения неполадок по умолчанию.
      MSSQL_ENABLE_HADR : "0" #Включение группы доступности. Например "1" включена и отключена "0" - репликация
      MSSQL_AGENT_ENABLED : "true" #Включите агент SQL Server. Например «true» включен, и «false» отключена. По умолчанию агент отключен.
      #MSSQL_MASTER_DATA_FILE" #Задает расположение файла данных базы данных master.
      #MSSQL_ERROR_LOG_FILE" #Задает расположение файла журнала базы данных master.
      #MSSQL_MASTER_LOG_FILE" #Задает расположение файлов журнала ошибок.    
    volumes:       
      - ./sqldata:/var/opt/sqlserver/data
      - ./sqllog:/var/opt/sqlserver/log
      - ./sqlbackup:/var/opt/sqlserver/backup
volumes:
  postgres-data:
  postgres-freetds:
  pgadmin:
  sqldata:
  sqllog:
  sqlbackup:
